map:
  bounds:
    x: 0
    y: 160
    width: 640
    height: 64
  boundaries:
    - id: boundary_1
      boundary_type: less_than_x
      x: 360
      enabled: true

billboards:
    - filename: images/rivercity-school.gif
      position:
        x: 0
        y: 0
      origin:
        x: 0
        y: 0
      scale:
        x: 1.5
        y: 1.5

actors:
  - id: npc_1
    actor_type: npc
    model: resources/model.yaml
    sprites: images/ryan.png
    spritesheet: resources/spritesheet.json
    state_name: standing
    frame_index: 0
    director: bot_1
    position: 
      x: 128
      y: 96
    health: 2
    full_health: 2
    facing_left: true
    enabled: true
  - id: pc
    actor_type: player
    model: resources/model.yaml
    sprites: images/alex.png
    spritesheet: resources/spritesheet.json
    state_name: standing
    frame_index: 0
    director: user_1
    position: 
      x: 64 
      y: 128
    health: 10
    full_health: 10
    facing_left: false
    enabled: true
  - id: npc_2
    actor_type: npc
    model: resources/model.yaml
    sprites: images/ryan.png
    spritesheet: resources/spritesheet.json
    state_name: standing
    frame_index: 0
    director: bot_2
    position: 
      x: 512 
      y: 64
    health: 5
    full_health: 5
    facing_left: true
    enabled: false

triggers:
  - id: npc_1_died
    trigger_type: npc_remove
    actor_id: npc_1
    fired: false
  - id: crossed_line
    trigger_type: left_right_cross
    x: 364
    fired: false

scripts:
    - id: turn_off_boundary
      trigger: npc_1_died
      command:
        command_type: boundary
        boundary_id: boundary_1
        enable: false
    - id: enable_npc_2
      trigger: crossed_line
      command:
        command_type: enable_actor
        actor_id: npc_2

